Repository D-PRlME/Togather-iOS, pull requests merged in 2022-11, with the labels that each got.

#254 🔀 :: (#202) add user profile
  Togather/Togather/Model/user/ProfileModel.swift
  Togather/Togather/Model/user/UserProfileModel.swift
  Togather/Togather/Network/MoyaClient/UserClient.swift
  Togather/Togather/Sources/Scene/Login/ViewModel/LoginViewModel.swift
  Togather/Togather/Sources/Scene/PostDetail/View/PostDetailView.swift
  Togather/Togather/Sources/Scene/PostDetail/View/UserProfileView.swift
  Togather/Togather/Sources/Scene/PostDetail/ViewModel/PostDetailViewModel.swift
  Togather/Togather/Sources/Scene/SignUp/ViewModel/SignUpViewModel.swift
  Togather/Togather/Sources/Scene/WritingPost/ViewModel/PostViewModel.swift
  Togather/Togather/ViewModels/user/Change/ChangeMyInfoViewModel.swift
  Togather/Togather/ViewModels/user/Change/ChangePasswordToEmailViewModel.swift
  Togather/Togather/ViewModels/user/Profile/GetMyProfileViewModel.swift
  Togather/Togather/ViewModels/user/Profile/GetUserProfileViewModel.swift
  Togather/Togather/ViewModels/user/Profile/UserProfileViewModel.swift
Labels: 기능 추가

#255 🔀 :: (#253) change var to let
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Sources/Components/Auth/AuthTextField.swift
  Togather/Togather/Sources/Components/Post/PostButton.swift
  Togather/Togather/Sources/Components/Post/PostTextEditor.swift
  Togather/Togather/Sources/Components/Post/PostTextField.swift
  Togather/Togather/Sources/Components/PostDetail/PostInfoForm.swift
  Togather/Togather/Sources/Components/Search/SearchTagLabel.swift
  Togather/Togather/Sources/Components/Search/SearchTextField.swift
  Togather/Togather/Sources/Scene/Home/Model/UserPostModel.swift
  Togather/Togather/Sources/Scene/PostDetail/Model/PostDetailModel.swift
  Togather/Togather/View/chat/ChatListView.swift
  Togather/Togather/View/chat/ChattingView.swift
  Togather/Togather/View/chat/MyChat.swift
  Togather/Togather/View/chat/OpponentChat.swift
Labels: 수정

#257 🔀 :: (#256) change profile image
  Togather/Togather.xcodeproj/xcshareddata/xcschemes/Togather.xcscheme
  Togather/Togather/Model/UploadImageModel.swift
  Togather/Togather/Model/user/UserProfileUDModel.swift
  Togather/Togather/Network/MoyaClient/ImageClient.swift
  Togather/Togather/Sources/Components/Home/PostForm.swift
  Togather/Togather/Sources/Scene/MyView/View/MyView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/DeleteAccountView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/EditInfoView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/ImagePicker.swift
  Togather/Togather/Sources/Scene/PostEdit/View/EditPostView.swift
  Togather/Togather/View/chat/ChatListView.swift
  Togather/Togather/ViewModels/user/Change/ChangeMyInfoViewModel.swift
Labels: 기능 추가

#259 🔀 :: (#258) 채팅 리스트 서버 연동
  Togather/Togather/Model/chat/ChatListModel.swift
  Togather/Togather/Network/MoyaClient/ChatClient.swift
  Togather/Togather/View/chat/ChatListView.swift
  Togather/Togather/ViewModels/chat/ChattingListViewModel.swift
Labels: 기능 추가

#261 🔀 :: (#260) 프로필 이미지 변경 버그
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Sources/Scene/MyView/View/MyView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/EditInfoView.swift
  Togather/Togather/ViewModels/user/Change/ChangeMyInfoViewModel.swift
Labels: 버그수정

#264 🔀 :: (#263) 계정 삭제 뷰 리팩토링
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Togather/Togather/Network/MoyaClient/ImageClient.swift
  Togather/Togather/Network/MoyaClient/PostClient.swift
  Togather/Togather/Network/MoyaClient/SocketClient.swift
  Togather/Togather/Network/MoyaClient/UserClient.swift
  Togather/Togather/Sources/Components/Auth/AuthButton.swift
  Togather/Togather/Sources/Components/MyView/ChagePassword/ChangePasswordButton.swift
  Togather/Togather/Sources/Components/MyView/ChagePassword/ChangePasswordTextField.swift
  Togather/Togather/Sources/Components/MyView/ChagePassword/ChangePasswordTitle.swift
  Togather/Togather/Sources/Components/MyView/DeleteAccount/DeleteAcountButton.swift
  Togather/Togather/Sources/Components/MyView/EditInfo/EditInfoTextEditor.swift
  Togather/Togather/Sources/Components/MyView/EditInfo/EditInfoTextField.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/DeleteAccountView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/EditInfoView.swift
  Togather/Togather/Sources/Scene/MyView/ViewModel/EditInfo/ChangeMyInfoViewModel.swift
  Togather/Togather/Sources/Scene/MyView/ViewModel/Logout/LogoutViewModel.swift
  Togather/Togather/Sources/Scene/MyView/ViewModel/QuitAccount/QuitAccountViewModel.swift
  Togather/Togather/View/ChangePasswordEmailView.swift
  Togather/Togather/View/ChangePasswordVerifyView.swift
  Togather/Togather/View/EnterNewPasswordView.swift
  Togather/Togather/ViewModels/user/ChangePasswordToEmailViewModel.swift
  Togather/Togather/ViewModels/user/TokenAuthViewModel.swift
  Togather/Togather/ViewModels/user/UserProfileViewModel.swift
Labels: 리팩토링

#266 🔀 :: (#265) 내 게시글 조회 뷰 리팩토링
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Network/MoyaClient/ChatClient.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/EditInfoView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/MyPostView.swift
  Togather/Togather/SupportingFiles/Preview Content/Preview Assets.xcassets/Contents.json
  Togather/Togather/ViewModels/ChattingListViewModel.swift
Labels: 리팩토링

#270 🔀 :: (#267) image refactoring
  Togather/Togather/Sources/Scene/MyView/View/myview ->/DeleteAccountView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/EditInfoView.swift
Labels: 버그수정, 기능 추가, 리팩토링

#275 🔀 :: (#274) 이미지 svg 수정
  Togather/Togather/Resources/Assets.xcassets/Image/CloseBtn.imageset/CloseBtn.png
  Togather/Togather/Resources/Assets.xcassets/Image/CloseBtn.imageset/CloseBtn.svg
  Togather/Togather/Resources/Assets.xcassets/Image/CloseBtn.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/Image/Eye.imageset/Eye.svg
  Togather/Togather/Resources/Assets.xcassets/Image/EyeDisable.imageset/EyeDisable.svg
  Togather/Togather/Resources/Assets.xcassets/Image/GrayHeart.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/Image/GrayHeart.imageset/GrayHeart.png
  Togather/Togather/Resources/Assets.xcassets/Image/GrayHeart.imageset/GrayHeart.svg
  Togather/Togather/Resources/Assets.xcassets/Image/LinkImage.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/Image/LinkImage.imageset/LinkIimage.png
  Togather/Togather/Resources/Assets.xcassets/Image/LinkImage.imageset/LinkImage.svg
  Togather/Togather/Resources/Assets.xcassets/Image/OffHeart.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/Image/OffHeart.imageset/OffHeart.svg
  Togather/Togather/Resources/Assets.xcassets/Image/OffHeart.imageset/Vector 1.png
  Togather/Togather/Resources/Assets.xcassets/Image/OnHeart.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/Image/OnHeart.imageset/OnHeart.svg
  Togather/Togather/Resources/Assets.xcassets/Image/OnHeart.imageset/Vector 1-1.png
  Togather/Togather/Resources/Assets.xcassets/Image/SeperateBar.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/Image/SeperateBar.imageset/SeperateBar.png
  Togather/Togather/Resources/Assets.xcassets/Image/SeperateBar.imageset/SeperateBar.svg
  Togather/Togather/Resources/Assets.xcassets/Image/WhiteCheck.imageset/WhiteCheck.svg
  Togather/Togather/Resources/Assets.xcassets/Image/back.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/Image/back.imageset/back.png
  Togather/Togather/Resources/Assets.xcassets/Image/back.imageset/back.svg
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/ChatOff.imageset/ChatOff.png
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/ChatOff.imageset/ChatOff.svg
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/ChatOff.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/HomeOff.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/HomeOff.imageset/HomeOff.svg
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/HomeOff.imageset/iconHome_Deselected@1X.png
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/MyOff.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/MyOff.imageset/MyOff.svg
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/MyOff.imageset/iconMy_Deselected@1X.png
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/SearchOff.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/SearchOff.imageset/SearchOff.svg
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/SearchOff.imageset/iconSearch_Deselected@1X.png
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/WritingOff.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/WritingOff.imageset/WritingOff.pdf
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/WritingOff.imageset/iconAdd_Deselected@1X.png
  Togather/Togather/Resources/Assets.xcassets/OnTabBarImage/ChatOn.imageset/ChatOn.png
  Togather/Togather/Resources/Assets.xcassets/OnTabBarImage/ChatOn.imageset/ChatOn.svg
  Togather/Togather/Resources/Assets.xcassets/OnTabBarImage/ChatOn.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/OnTabBarImage/HomeOn.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/OnTabBarImage/HomeOn.imageset/HomeOn.svg
  Togather/Togather/Resources/Assets.xcassets/OnTabBarImage/HomeOn.imageset/iconHome_Selected@1X.png
  Togather/Togather/Resources/Assets.xcassets/OnTabBarImage/MyOn.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/OnTabBarImage/MyOn.imageset/MyOn.svg
  Togather/Togather/Resources/Assets.xcassets/OnTabBarImage/MyOn.imageset/iconMy_Selected@1X.png
  Togather/Togather/Resources/Assets.xcassets/OnTabBarImage/SearchOn.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/OnTabBarImage/SearchOn.imageset/SearchOn.svg
  Togather/Togather/Resources/Assets.xcassets/OnTabBarImage/SearchOn.imageset/iconSearch_Selected@1X.png
  Togather/Togather/Resources/Assets.xcassets/OnTabBarImage/WritingOn.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/OnTabBarImage/WritingOn.imageset/iconAdd_Selected@1X.png
  Togather/Togather/Sources/Components/Auth/AuthTextField.swift
Labels: 리팩토링, 수정

#280 🔧 :: (#279) swift lint
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/.swiftlint.yml
Labels: 프로젝트 설정

#289 🔀 :: (#288) 소켓 통신 테스트
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Soket/View/SocketTest.swift
  Togather/Togather/Soket/View/SocketView.swift
  Togather/Togather/Soket/ViewModel/SocketViewModel.swift
  Togather/Togather/Sources/Application/ToGatherApp.swift
Labels: 기능 추가

#297 🔀 :: swiftkeychain library
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Togather/Togather/Model/user/UserProfileUDModel.swift
  Togather/Togather/Network/Header/Header.swift
Labels: 기능 추가

#301 🔀 :: lint 함수 최대 길이 제외
  Togather/Togather/.swiftlint.yml
Labels: 기능 추가

#303 🔀 :: edit alert
  Togather/Togather/Sources/Components/Home/PostForm.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/DeleteAccountView.swift
  Togather/Togather/Sources/Scene/PostDetail/View/PostDetailView.swift
Labels: 기능 추가

#305 🔀 :: (#304) View, ViewModel Refactoring
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Resources/Launch Screen.storyboard
  Togather/Togather/Soket/View/SocketTest.swift
  Togather/Togather/Sources/Application/ContentView.swift
  Togather/Togather/Sources/Application/ContentViewModel.swift
  Togather/Togather/Sources/Components/Auth/SignUp/EmailVerifyTitle.swift
  Togather/Togather/Sources/Scene/ChangePassword/Model/ChangePasswordModel.swift
  Togather/Togather/Sources/Scene/ChangePassword/View/ChangePasswordEmailView.swift
  Togather/Togather/Sources/Scene/ChangePassword/View/ChangePasswordSuccessView.swift
  Togather/Togather/Sources/Scene/ChangePassword/View/ChangePasswordVerifyView.swift
  Togather/Togather/Sources/Scene/ChangePassword/View/EnterNewPasswordView.swift
  Togather/Togather/Sources/Scene/ChangePassword/ViewModel/ChangePasswordEmailViewModel.swift
  Togather/Togather/Sources/Scene/ChangePassword/ViewModel/ChangePasswordVerifyViewModel.swift
  Togather/Togather/Sources/Scene/ChangePassword/ViewModel/EnterNewPasswordViewModel.swift
  Togather/Togather/Sources/Scene/Chat/View/ChatListView.swift
  Togather/Togather/Sources/Scene/Chat/ViewModel/ChatListViewModel.swift
  Togather/Togather/Sources/Scene/Home/View/HomeView.swift
  Togather/Togather/Sources/Scene/MyView/Model/MyModel.swift
  Togather/Togather/Sources/Scene/MyView/View/MyView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/DeleteAccountView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/DevelopersView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/EditInfoView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/ImagePicker.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/MyPostView.swift
  Togather/Togather/Sources/Scene/MyView/ViewModel/EditInfo/ChangeMyInfoViewModel.swift
  Togather/Togather/Sources/Scene/MyView/ViewModel/Logout/MyViewModel.swift
  Togather/Togather/Sources/Scene/PostEdit/View/EditPostView.swift
  Togather/Togather/Sources/Scene/SignUp/SignUpTextField/SignUpTextField.swift
  Togather/Togather/Sources/Scene/SignUp/View/SignUpEmailVerifyView.swift
  Togather/Togather/Sources/Scene/SignUp/View/SignUpSuccessView.swift
  Togather/Togather/Sources/Scene/SignUp/View/SignUpView.swift
  Togather/Togather/Sources/Scene/SignUp/ViewModel/SignUpEmailVerifyViewModel.swift
  Togather/Togather/Sources/Scene/SignUp/ViewModel/SignUpSuccessViewModel.swift
  Togather/Togather/Sources/Scene/SignUp/ViewModel/SignUpValueCheckViewModel.swift
  Togather/Togather/Sources/Scene/SignUp/ViewModel/SignUpViewModel.swift
  Togather/Togather/Sources/Scene/TabBar/View/TabBarView.swift
  Togather/Togather/Sources/Scene/TagList/View/SearchTagListView.swift
  Togather/Togather/Sources/Scene/TagList/View/TagListView.swift
  Togather/Togather/Sources/Scene/TagList/ViewModel/SearchTagListViewModel.swift
  Togather/Togather/Sources/Scene/TagList/ViewModel/TagListViewModel.swift
  Togather/Togather/Sources/Scene/WritingPost/View/WritingView.swift
  Togather/Togather/Sources/Scene/WritingPost/ViewModel/WritingViewModel.swift
Labels: 리팩토링

#307 🔀 :: (#306) QuitAccountViewModel
  Togather/Togather/Sources/Scene/MyView/ViewModel/QuitAccount/QuitAccountViewModel.swift
Labels: 기능 추가

#312 🔀 :: (#311) delete 주석
  Togather/Togather/Sources/Components/MyView/DeleteAccount/DeleteAcountButton.swift
  Togather/Togather/Sources/Components/MyView/EditInfo/EditInfoTextEditor.swift
  Togather/Togather/Sources/Components/Post/PostButton.swift
  Togather/Togather/Sources/Scene/LoginChangePassword/VIew/ChangePasswordEmailSuccessView.swift
Labels: 수정

#313 🔀 :: (#293) 채팅 뷰에 약간의 기능 추가
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Network/Header/Header.swift
  Togather/Togather/Network/MoyaClient/ChatClient.swift
  Togather/Togather/Network/MoyaClient/SocketClient.swift
  Togather/Togather/Soket/View/SocketTest.swift
  Togather/Togather/Sources/Scene/Chat/Model/ChatListModel.swift
  Togather/Togather/Sources/Scene/Chat/Model/ChattingDataModel.swift
  Togather/Togather/Sources/Scene/Chat/View/ChatListView.swift
  Togather/Togather/Sources/Scene/Chat/View/ChattingView.swift
  Togather/Togather/Sources/Scene/Chat/ViewModel/ChatListViewModel.swift
  Togather/Togather/Sources/Scene/Chat/ViewModel/SocketViewModel.swift
  Togather/Togather/SupportingFiles/Info.plist
Labels: 기능 추가

#320 🔀 :: (#318) lint 수정
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Network/MoyaClient/ChatClient.swift
  Togather/Togather/Soket/View/SocketTest.swift
  Togather/Togather/Sources/Components/Chat/OpponentChat.swift
  Togather/Togather/Sources/Scene/Chat/Model/ChattingDataModel.swift
  Togather/Togather/Sources/Scene/Chat/View/ChatListView.swift
  Togather/Togather/Sources/Scene/Chat/View/ChattingView.swift
  Togather/Togather/Sources/Scene/Chat/ViewModel/ChatListViewModel.swift
  Togather/Togather/Sources/Scene/Chat/ViewModel/SocketViewModel.swift
Labels: 버그수정, 수정

#321 🔀 :: (#316) 게시물 수정 버그 수정
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Sources/Scene/Chat/View/ChattingView.swift
  Togather/Togather/Sources/Scene/PostDetail/View/PostDetailView.swift
  Togather/Togather/Sources/Scene/PostEdit/View/EditPostView.swift
Labels: 버그수정

#323 🔀 :: (#322) 실시간 채팅 구현
  Togather/Togather/Sources/Scene/Chat/View/ChatListView.swift
  Togather/Togather/Sources/Scene/Chat/View/ChattingView.swift
  Togather/Togather/Sources/Scene/Chat/ViewModel/ChatListViewModel.swift
  Togather/Togather/Sources/Scene/PostDetail/View/PostDetailView.swift
Labels: 기능 추가

#326 🔀 :: (#324) 연락 하기 기능
  Togather/Togather/Sources/Components/Home/PostForm.swift
  Togather/Togather/Sources/Scene/Home/View/HomeView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/MyPostView.swift
  Togather/Togather/Sources/Scene/PostDetail/View/PostDetailView.swift
  Togather/Togather/Sources/Scene/PostDetail/ViewModel/PostDetailViewModel.swift
  Togather/Togather/Sources/Scene/Search/View/SearchView.swift
  Togather/Togather/Sources/Scene/TabBar/View/ShowView.swift
Labels: 기능 추가

#327 🔀 :: (#325) 채팅 기능 추가 및 수정
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Network/MoyaClient/ChatClient.swift
  Togather/Togather/Sources/Scene/Chat/View/ChattingView.swift
  Togather/Togather/Sources/Scene/Chat/ViewModel/ChatListViewModel.swift
Labels: 기능 추가, 수정
