Repository D-PRlME/Togather-iOS, pull requests merged in 2022-12, with the labels that each got.

#332 🔀 :: (#331) 채팅 스켈레톤 완성
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Sources/Components/Chat/ChattingSkeleton.swift
  Togather/Togather/Sources/Components/Chat/MychatSkeleton.swift
  Togather/Togather/Sources/Components/Chat/OpponentChatSkeleton.swift
  Togather/Togather/Sources/Extension/Date+timeFormat.swift
  Togather/Togather/Sources/Scene/Chat/View/ChatListView.swift
  Togather/Togather/Sources/Scene/Chat/View/ChattingView.swift
Labels: 기능 추가

#334 🔀 :: (#333) 키보드 클릭시 dissmis
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Sources/Components/BackgroundTapGesture/BackgroundTapGesture.swift
  Togather/Togather/Sources/Extension/UIApplication+endEditing.swift
  Togather/Togather/Sources/Scene/ChangePassword/View/ChangePasswordVerifyView.swift
  Togather/Togather/Sources/Scene/ChangePassword/View/EnterNewPasswordView.swift
  Togather/Togather/Sources/Scene/Chat/View/ChattingView.swift
  Togather/Togather/Sources/Scene/Chat/ViewModel/ChatListViewModel.swift
  Togather/Togather/Sources/Scene/Login/View/LoginView.swift
  Togather/Togather/Sources/Scene/LoginChangePassword/VIew/ChangeLostPasswordView.swift
  Togather/Togather/Sources/Scene/LoginChangePassword/VIew/ChangePasswordEmailView.swift
  Togather/Togather/Sources/Scene/LoginChangePassword/VIew/EmailVerifyView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/EditInfoView.swift
  Togather/Togather/Sources/Scene/PostEdit/View/EditPostView.swift
  Togather/Togather/Sources/Scene/Search/View/SearchView.swift
  Togather/Togather/Sources/Scene/SignUp/View/SignUpEmailVerifyView.swift
  Togather/Togather/Sources/Scene/SignUp/View/SignUpView.swift
  Togather/Togather/Sources/Scene/WritingPost/View/WritingView.swift
  Togather/Togather/SupportingFiles/Info.plist
Labels: 기능 추가

#336 🔀 :: (#335) 버그 수정
  Togather/Togather/Resources/Assets.xcassets/Image.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/Image/gray_logo.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/Image/gray_logo.imageset/gray_logo.svg
  Togather/Togather/Sources/Scene/Chat/View/ChatListView.swift
  Togather/Togather/Sources/Scene/Chat/View/ChattingView.swift
  Togather/Togather/Sources/Scene/Chat/ViewModel/ChatListViewModel.swift
  Togather/Togather/Sources/Scene/PostDetail/View/PostDetailView.swift
  Togather/Togather/Sources/Scene/Search/View/SearchView.swift
  Togather/Togather/Sources/Scene/TabBar/View/ShowView.swift
  Togather/Togather/Sources/Scene/UserProfile/View/UserProfileView.swift
Labels: 버그수정

#338 🔀 :: (#337) 채팅 파일 구조 변경
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Network/MoyaClient/ChatClient.swift
  Togather/Togather/Sources/Scene/Chat/Model/ChattingDataModel.swift
  Togather/Togather/Sources/Scene/Chat/View/ChattingView.swift
  Togather/Togather/Sources/Scene/Chat/ViewModel/ChatListViewModel.swift
  Togather/Togather/Sources/Scene/Chat/ViewModel/ChattingViewModel.swift
  Togather/Togather/Sources/Scene/Chat/ViewModel/SocketViewModel.swift
  Togather/Togather/Sources/Scene/PostDetail/View/PostDetailView.swift
  Togather/Togather/SupportingFiles/Info.plist
Labels: 수정

#340 🔀 :: (#339) textfield, texteditor, component 파일 수정 및 추가
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Resources/Launch Screen.storyboard
  Togather/Togather/Sources/Components/ContentTextEditor.swift
  Togather/Togather/Sources/Components/MyView/EditInfo/EditInfoTextEditor.swift
  Togather/Togather/Sources/Components/MyView/EditInfo/EditInfoTextField.swift
  Togather/Togather/Sources/Components/Post/PostTextEditor.swift
  Togather/Togather/Sources/Components/Post/PostTextField.swift
  Togather/Togather/Sources/Components/TitleTextField.swift
  Togather/Togather/Sources/Extension/String+positionTypeChange.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/EditInfoView.swift
  Togather/Togather/Sources/Scene/PostEdit/View/EditPostView.swift
  Togather/Togather/Sources/Scene/WritingPost/View/WritingView.swift
Labels: 수정

#342 🔀 :: (#341) 최종 버그 디버깅
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Network/Header/Header.swift
  Togather/Togather/Network/MoyaClient/UserClient.swift
  Togather/Togather/Sources/Components/Chat/OpponentChat.swift
  Togather/Togather/Sources/Scene/ChangePassword/ViewModel/ChangePasswordVerifyViewModel.swift
  Togather/Togather/Sources/Scene/Chat/View/ChatListView.swift
  Togather/Togather/Sources/Scene/Chat/ViewModel/ChatListViewModel.swift
  Togather/Togather/Sources/Scene/Login/LoginButton/LoginImageButton.swift
  Togather/Togather/Sources/Scene/Login/View/LoginView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/DeleteAccountView.swift
  Togather/Togather/View/HomeView.swift
Labels: 버그수정
