Repository D-PRlME/Togather-iOS, pull requests merged in 2022-10, with the labels that each got.

#185 🔀 :: (#183) 소켓 테스트
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Togather/Togather/ContentView.swift
  Togather/Togather/Header/Header.swift
  Togather/Togather/Model/post/DumyData.swift
  Togather/Togather/MoyaClient/PostClient.swift
  Togather/Togather/MoyaClient/SocketClient.swift
  Togather/Togather/Soket/SocketTest.swift
  Togather/Togather/Soket/SocketViewModel.swift
  Togather/Togather/View/HomeView.swift
  Togather/Togather/View/PostDetailVIew.swift
  Togather/Togather/ViewModels/post/postDetailViewModel.swift
Labels: 기능 추가

#186 🔀 :: (#184) 뒤로가기 추가
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Togather/Togather/Assets.xcassets/Image/back.imageset/Contents.json
  Togather/Togather/Assets.xcassets/Image/back.imageset/back.png
  Togather/Togather/View/SignUpView/SignUpEmailVerifyView.swift
  Togather/Togather/View/SignUpView/SignUpView.swift
  Togather/Togather/View/compenent/BackBtn.swift
  Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordVerifyView.swift
Labels: 기능 추가, 뷰

#188 🔀 :: (#187) BackgroundColor 변수 이름 변경
  Togather/Togather/ContentView.swift
  Togather/Togather/View/HomeView.swift
  Togather/Togather/View/MyView.swift
  Togather/Togather/View/PostDetailVIew.swift
  Togather/Togather/View/SearchView.swift
  Togather/Togather/View/SignInView.swift
  Togather/Togather/View/myview ->/DeleteAccount.swift
  Togather/Togather/View/myview ->/Developers.swift
  Togather/Togather/View/myview ->/EditInfo.swift
  Togather/Togather/View/myview ->/MyPost.swift
  Togather/Togather/ViewModels/user/Email/EmailVerifyViewModel.swift
Labels: 수정

#192 🔀 :: (#191) 내프로필 뷰
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Assets.xcassets/Color/Contents.json
  Togather/Togather/Model/user/MyProfileModel.swift
  Togather/Togather/MoyaClient/UserClient.swift
  Togather/Togather/View/C언어 ㅋ.c
  Togather/Togather/View/C언어 ㅋ.h
  Togather/Togather/View/EditPostView.swift
  Togather/Togather/View/HomeView.swift
  Togather/Togather/View/PostDetailVIew.swift
  Togather/Togather/View/SearchView.swift
  Togather/Togather/View/TagListView.swift
  Togather/Togather/View/WritingView.swift
  Togather/Togather/View/myview ->/EditInfo.swift
  Togather/Togather/View/myview ->/MyPost.swift
  Togather/Togather/ViewModels/user/Change/ChangeMyInfoViewModel.swift
Labels: 뷰

#193 🔀 :: (#129) 내정보 수정 기능
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Togather/Togather/MoyaClient/UserClient.swift
  Togather/Togather/View/MyView.swift
  Togather/Togather/View/myview ->/DeleteAccountView.swift
  Togather/Togather/View/myview ->/DevelopersView.swift
  Togather/Togather/View/myview ->/EditInfoView.swift
  Togather/Togather/View/myview ->/MyPostView.swift
  Togather/Togather/ViewModels/user/Change/ChangeMyInfoViewModel.swift
Labels: 기능 추가

#195 🔀 :: (#194) 프로필 포지션 태그 UI
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Extension/PositionChangeExtension.swift
  Togather/Togather/Model/user/UserProfileUDModel.swift
  Togather/Togather/View/MyView.swift
  Togather/Togather/View/myview ->/EditInfoView.swift
  Togather/Togather/ViewModels/user/Change/ChangeMyInfoViewModel.swift
  Togather/Togather/ViewModels/user/Login/LoginViewModel.swift
  Togather/Togather/ViewModels/user/SignUp/SignUpViewModel.swift
Labels: 기능 추가

#197 🔀 :: (#196) 비밀번호 변경 이메일 인증 뷰
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordEmailView.swift
Labels: 뷰

#199 🔀 :: (#198) 색상추가
  Togather/Togather/Assets.xcassets/Color/main-Elevated.colorset/Contents.json
  Togather/Togather/Assets.xcassets/Color/main.colorset/Contents.json
  Togather/Togather/Assets.xcassets/Color/red.colorset/Contents.json
  Togather/Togather/Assets.xcassets/Color/white-Elevated1.colorset/Contents.json
  Togather/Togather/Assets.xcassets/Color/white-Elevated2.colorset/Contents.json
  Togather/Togather/Assets.xcassets/Color/white-Elevated3.colorset/Contents.json
  Togather/Togather/Assets.xcassets/Color/white-Elevated4.colorset/Contents.json
  Togather/Togather/Assets.xcassets/Color/white.colorset/Contents.json
Labels: 뷰

#201 🔀 :: (#200) 디자인 시스템 색상
  Togather/Togather/Assets.xcassets/Color/text0.colorset/Contents.json
Labels: 수정

#204 🔀 :: (#203) 비밀번호 변경 VM 연결
  Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordEmailView.swift
Labels: 기능 추가

#206 🔀 :: (#205) 로그인 오류처리
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/ContentView.swift
  Togather/Togather/View/LoginView.swift
  Togather/Togather/View/MyView.swift
  Togather/Togather/View/myview ->/EditInfoView.swift
  Togather/Togather/ViewModels/user/Login/LoginViewModel.swift
Labels: 기능 추가

#216 🔀 :: (#213) 회원가입 뷰 리팩토링
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Network/Header/Header.swift
  Togather/Togather/Network/MoyaClient/PostClient.swift
  Togather/Togather/Network/MoyaClient/SocketClient.swift
  Togather/Togather/Network/MoyaClient/UserClient.swift
  Togather/Togather/Network/Plugin/MoyaLoggerPlugin.swift
  Togather/Togather/Resources/Launch Screen.storyboard
  Togather/Togather/Sources/Components/Auth/AuthButton.swift
  Togather/Togather/Sources/Components/Auth/AuthTextField.swift
  Togather/Togather/Sources/Components/Auth/SignUp/EmailVerifyTitle.swift
  Togather/Togather/Sources/Components/Auth/SignUp/SignUpTitle.swift
  Togather/Togather/Sources/Extension/String+PositionTypeChange.swift
  Togather/Togather/Sources/Scene/Login/LoginTextField/LoginTextField.swift
  Togather/Togather/Sources/Scene/SignUp/EmailVerifyTextField/EmailVerifyTextField.swift
  Togather/Togather/Sources/Scene/SignUp/SignUpTextField/SignUpTextField.swift
  Togather/Togather/Sources/Scene/SignUp/View/SignUpEmailVerifyView.swift
  Togather/Togather/Sources/Scene/SignUp/View/SignUpView.swift
  Togather/Togather/Sources/Scene/SignUp/View/signUpSuccessView.swift
  Togather/Togather/Sources/Scene/SignUp/ViewModel/SignUpValueCheckViewModel.swift
  Togather/Togather/Sources/Scene/SignUp/ViewModel/SignUpViewModel.swift
  Togather/Togather/SupportingFiles/Info.plist
  Togather/Togather/View/SignUpView/SignUpEmailVerifyView.swift
  Togather/Togather/View/SignUpView/SignUpView.swift
  Togather/Togather/ViewModels/user/Email/SendEmailViewModel.swift
  Togather/Togather/ViewModels/user/SignUp/SignUpViewModel.swift
Labels: 리팩토링

#217 🔀 :: (#214) 인증번호 뷰 리팩토링
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Sources/Application/ContentView.swift
  Togather/Togather/Sources/Application/DrawApp.swift
  Togather/Togather/Sources/Scene/SignUp/View/SignUpEmailVerifyView.swift
  Togather/Togather/Sources/Scene/SignUp/View/signUpSuccessView.swift
Labels: 리팩토링

#221 🔀 :: (#220) TabView 리팩토링
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/ChatOff.imageset/ChatOff.png
  Togather/Togather/Resources/Assets.xcassets/OffTabBarImage/ChatOff.imageset/Contents.json
  Togather/Togather/Resources/Assets.xcassets/OnTabBarImage/ChatOn.imageset/ChatOn.png
  Togather/Togather/Resources/Assets.xcassets/OnTabBarImage/ChatOn.imageset/Contents.json
  Togather/Togather/Resources/Color/Color.swift
  Togather/Togather/View/MyView.swift
  Togather/Togather/View/TabBarView.swift
  Togather/Togather/View/chat/ChatListView.swift
  Togather/Togather/View/chat/ChattingView.swift
Labels: 리팩토링

#222 🔀 :: (#218) 홈뷰 리팩토링
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Sources/Application/ContentView.swift
  Togather/Togather/Sources/Components/Home/PostForm.swift
  Togather/Togather/Sources/Components/Home/TagSelectList.swift
  Togather/Togather/Sources/Scene/Home/Model/UserPostModel.swift
  Togather/Togather/Sources/Scene/Home/View/HomeView.swift
  Togather/Togather/Sources/Scene/Home/ViewModel/HomeViewModel.swift
  Togather/Togather/View/HomeView.swift
  Togather/Togather/View/PostDetailVIew.swift
  Togather/Togather/View/SearchView.swift
  Togather/Togather/View/myview ->/MyPostView.swift
  Togather/Togather/ViewModels/post/postDetailViewModel.swift
Labels: 리팩토링

#225 🔀 :: (#224) tabbarview 리팩토링
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Togather/Togather/View/ShowView.swift
  Togather/Togather/View/TabBarView.swift
  Togather/Togather/View/chat/ChatListView.swift
  Togather/Togather/View/chat/ChattingView.swift
Labels: 리팩토링

#227 🔀 :: (#226) 오류 해결
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Sources/Application/ContentView.swift
  Togather/Togather/Sources/Components/Home/PostForm.swift
  Togather/Togather/View/HomeView.swift
  Togather/Togather/View/PostDetailVIew.swift
  Togather/Togather/View/ShowView.swift
  Togather/Togather/View/TabBarView.swift
  Togather/Togather/View/chat/ChatListView.swift
  Togather/Togather/View/chat/ChattingView.swift
Labels: 버그수정, Document

#230 🔀 :: (#229) 세부 게시물 뷰 리팩토링
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Togather/Togather/Model/post/PostDetailModel.swift
  Togather/Togather/Resources/Font/Font.swift
  Togather/Togather/Sources/Components/PostDetail/PostInfoForm.swift
  Togather/Togather/Sources/Scene/Login/LoginButton/LoginNavigationButton.swift
  Togather/Togather/Sources/Scene/PostDetail/View/PostDetailView.swift
  Togather/Togather/View/chat/ChattingView.swift
  Togather/Togather/ViewModels/post/postDetailViewModel.swift
Labels: 리팩토링

#236 🔀 :: (#233) 모든 테그 보기 뷰 리팩토링
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Sources/Scene/TagList/View/SearchTagListView.swift
  Togather/Togather/Sources/Scene/TagList/View/TagListView.swift
  Togather/Togather/Sources/Scene/TagList/ViewModel/TagViewModel.swift
Labels: 리팩토링

#237 🔀 :: (#235) 검색 뷰 리팩토링
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Network/MoyaClient/PostClient.swift
  Togather/Togather/Sources/Components/Home/PostForm.swift
  Togather/Togather/Sources/Components/Search/SearchTagLabel.swift
  Togather/Togather/Sources/Components/Search/SearchTextField.swift
  Togather/Togather/Sources/Scene/PostDetail/Model/PostDetailModel.swift
  Togather/Togather/Sources/Scene/PostDetail/View/PostDetailView.swift
  Togather/Togather/Sources/Scene/PostDetail/ViewModel/PostDetailViewModel.swift
  Togather/Togather/Sources/Scene/PostEdit/View/EditPostView.swift
  Togather/Togather/Sources/Scene/PostEdit/ViewModel/EditPostViewModel.swift
  Togather/Togather/Sources/Scene/Search/View/SearchView.swift
  Togather/Togather/Sources/Scene/Search/ViewModel/SearchViewModel.swift
  Togather/Togather/Sources/Scene/WritingPost/View/WritingView.swift
  Togather/Togather/Sources/Scene/WritingPost/ViewModel/PostViewModel.swift
  Togather/Togather/View/SearchView.swift
Labels: 리팩토링

#239 ♻️ :: TabBar 리팩토링
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Model/chat/ChatListModel.swift
  Togather/Togather/Sources/Scene/Home/View/HomeView.swift
  Togather/Togather/Sources/Scene/Login/LoginButton/LoginNavigationButton.swift
  Togather/Togather/View/TabBarView.swift
  Togather/Togather/View/chat/ChatListView.swift
  Togather/Togather/View/chat/ChattingView.swift
Labels: 리팩토링

#241 🔀 :: (#240) 검색 뷰 버그 수정
  Togather/Togather/Sources/Scene/Search/View/SearchView.swift
  Togather/Togather/Sources/Scene/WritingPost/View/WritingView.swift
Labels: 버그수정

#244 🔀 :: (#238) 프로필 이미지 변경
  Togather/Togather/Network/MoyaClient/ImageClient.swift
  Togather/Togather/View/myview ->/EditInfoView.swift
  Togather/Togather/View/myview ->/ImagePicker.swift
  Togather/Togather/ViewModels/user/Change/ChangeMyInfoViewModel.swift
Labels: 기능 추가

#247 🔀 :: (#246) tabbar refactoring
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Sources/Components/TabBar/SearchModalButton.swift
  Togather/Togather/Sources/Components/TabBar/TabBarItem.swift
  Togather/Togather/Sources/Scene/TabBar/View/ShowView.swift
  Togather/Togather/Sources/Scene/TabBar/View/TabBarView.swift
  Togather/Togather/View/TabBarView.swift
Labels: 리팩토링

#248 🔀 :: (#242) 내 프로필 뷰 리팩토링
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Sources/Components/MyView/MyViewButton.swift
  Togather/Togather/Sources/Scene/MyView/View/MyView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/CloseBtn.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/DeleteAccountView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/DevelopersView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/EditInfoView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/ImagePicker.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/MyPostView.swift
  Togather/Togather/View/ChangePasswordEmailView.swift
  Togather/Togather/View/ChangePasswordSuccessView.swift
  Togather/Togather/View/ChangePasswordVerifyView.swift
  Togather/Togather/View/EnterNewPasswordView.swift
  Togather/Togather/View/MyView.swift
Labels: 리팩토링

#250 🔀 :: (#249) private 추가
  Togather/Togather/Sources/Components/Home/PostForm.swift
  Togather/Togather/Sources/Scene/Home/View/HomeView.swift
  Togather/Togather/Sources/Scene/Login/View/LoginView.swift
  Togather/Togather/Sources/Scene/MyView/View/MyView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/DeleteAccountView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/EditInfoView.swift
  Togather/Togather/Sources/Scene/MyView/View/myview ->/MyPostView.swift
  Togather/Togather/Sources/Scene/PostEdit/View/EditPostView.swift
  Togather/Togather/Sources/Scene/Search/View/SearchView.swift
  Togather/Togather/Sources/Scene/TabBar/View/TabBarView.swift
  Togather/Togather/Sources/Scene/WritingPost/View/WritingView.swift
  Togather/Togather/View/ChangePasswordSuccessView.swift
Labels: 수정
