Repository D-PRlME/Togather-iOS, pull requests merged in 2022-09, with the labels that each got.

#4 🔀 :: (#3) HomeView 태그 간격 조절
  Draw/Draw/View/HomeView.swift
Labels: 수정

#7 🔀 :: (#6) Launch Screen 추가
  Draw/Draw.xcodeproj/project.pbxproj
  Draw/Draw/Assets.xcassets/LOGO.imageset/Contents.json
  Draw/Draw/Assets.xcassets/LOGO.imageset/Logo.png
  Draw/Draw/Font/Pretendard-Black.otf
  Draw/Draw/Font/Pretendard-Bold.otf
  Draw/Draw/Font/Pretendard-ExtraBold.otf
  Draw/Draw/Font/Pretendard-ExtraLight.otf
  Draw/Draw/Font/Pretendard-Light.otf
  Draw/Draw/Font/Pretendard-Medium.otf
  Draw/Draw/Font/Pretendard-Regular.otf
  Draw/Draw/Font/Pretendard-SemiBold.otf
  Draw/Draw/Font/Pretendard-Thin.otf
  Draw/Draw/Launch Screen.storyboard
Labels: 기능 추가

#8 🔀 :: (#5) SearchView UI
  Draw/Draw/View/HomeView.swift
  Draw/Draw/View/SearchView.swift
  Draw/Draw/View/TabBarView.swift
Labels: 뷰

#10 🔀 :: (#9) MyView UI
  Draw/Draw/View/MyView.swift
Labels: 뷰

#16 📝 :: 글작성 UI
  Draw/Draw/Assets.xcassets/CloseBtn.imageset/CloseBtn.png
  Draw/Draw/Assets.xcassets/CloseBtn.imageset/Contents.json
  Draw/Draw/Assets.xcassets/Stroke/Contents.json
  Draw/Draw/Assets.xcassets/Stroke/RedStroke.colorset/Contents.json
  Draw/Draw/Assets.xcassets/Stroke/YellowStroke.colorset/Contents.json
  Draw/Draw/View/EditInfo/CloseBtn.swift
  Draw/Draw/View/EditInfo/DeleteAccount.swift
  Draw/Draw/View/EditInfo/EditInfo.swift
  Draw/Draw/View/WritingView.swift
Labels: 뷰

#18 🔀 :: (#17) 각 뷰 Stroke 방식 변경(리펙토링)
  Draw/Draw.xcodeproj/project.pbxproj
  Draw/Draw/View/HomeView.swift
  Draw/Draw/View/MyView.swift
  Draw/Draw/View/SearchView.swift
  Draw/Draw/View/TabBarView.swift
Labels: 리팩토링

#19 🔀 :: (#11) 계정 정보 수정 UI
  Draw/Draw/View/EditInfo/DeleteAccount.swift
  Draw/Draw/View/EditInfo/EditInfo.swift
Labels: 뷰

#21 🔀 :: (#20) 각 뷰의 stroke 방식 리팩토링
  Draw/Draw/View/HomeView.swift
  Draw/Draw/View/SearchView.swift
  Draw/Draw/View/WritingView.swift
Labels: 리팩토링

#23 🔀 :: (#22) 게시물 내용 UI
  Draw/Draw.xcodeproj/project.pbxproj
  Draw/Draw/Assets.xcassets/LinkImage.imageset/Contents.json
  Draw/Draw/Assets.xcassets/LinkImage.imageset/LinkIimage.png
  Draw/Draw/View/myview ->/CloseBtn.swift
  Draw/Draw/View/myview ->/DeleteAccount.swift
  Draw/Draw/View/myview ->/Developers.swift
  Draw/Draw/View/myview ->/EditInfo.swift
  Draw/Draw/View/myview ->/PostDetail.swift
Labels: 뷰

#24 🔀 :: (#14) 개발자들 UI
  Draw/Draw/ContentView.swift
  Draw/Draw/View/myview ->/Developers.swift
Labels: 뷰

#27 🔀 :: (#26) 노란색 오류 수정
  Draw/Draw/View/MyView.swift
  Draw/Draw/View/SearchView.swift
  Draw/Draw/View/TabBarView.swift
Labels: 버그수정

#29 🔀 :: (#28) 회원가입 절차 UI
  Draw/Draw.xcodeproj/project.pbxproj
  Draw/Draw/Assets.xcassets/GreenCheck.imageset/Contents.json
  Draw/Draw/Assets.xcassets/GreenCheck.imageset/green_check.png
  Draw/Draw/Assets.xcassets/PostBox.imageset/Contents.json
  Draw/Draw/Assets.xcassets/PostBox.imageset/post_box.png
  Draw/Draw/View/SignUpView/SignUpEmailVerifyView.swift
  Draw/Draw/View/SignUpView/SignUpView.swift
  Draw/Draw/View/SignUpView/signUpSuccessView.swift
Labels: 뷰

#33 🔀 :: (#31) SignUpView 관련 코드 리팩토링
  Draw/Draw/View/SearchView.swift
  Draw/Draw/View/SignUpView/SignUpEmailVerifyView.swift
  Draw/Draw/View/SignUpView/SignUpView.swift
  Draw/Draw/View/SignUpView/signUpSuccessView.swift
  Draw/Draw/View/WritingView.swift
  Draw/Draw/View/myview ->/EditInfo.swift
Labels: 리팩토링

#35 🔀 :: (#34) SigninView '로그인' 버튼 추가
  Draw/Draw/View/SignInView.swift
Labels: 뷰

#39 🔀 :: (#38) 작은 iPhone UI
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/View/HomeView.swift
  Togather/Togather/View/MyView.swift
  Togather/Togather/View/PostDetail.swift
  Togather/Togather/View/SearchView.swift
  Togather/Togather/View/TabBarView.swift
Labels: 뷰

#41 🔀 :: (#40) 충돌 버그 수정
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Togather/Togather.xcodeproj/xcshareddata/xcschemes/Togather.xcscheme
Labels: 버그수정

#42 🔀 :: (#12) 비밀번호 변경 UI
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/View/PasswordChangeView/ChangePasswordSuccess.swift
  Togather/Togather/View/PasswordChangeView/ChangePasswordVerify.swift
  Togather/Togather/View/PasswordChangeView/EnterNewPassword.swift
Labels: 뷰

#44 🔀 :: (#43) 비밀번호 변경 뷰 리팩토링
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordSuccess.swift
  Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordVerify.swift
  Togather/Togather/View/myview ->/PasswordChangeView/EnterNewPassword.swift
Labels: 리팩토링

#48 🔀 :: (#45) 클라이언트 코드 리팩토링
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/MoyaClient/PostClient.swift
  Togather/Togather/MoyaClient/UserClient.swift
Labels: 리팩토링

#47 🔀 :: (#46) 모델 생성
  Togather/Togather/Model/ErrorModel.swift
  Togather/Togather/Model/TokenModel.swift
Labels: 기능 추가

#50 🔀 :: (#49) Model 만들기
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Model/ErrorModel.swift
  Togather/Togather/Model/LookUpMyProfileModel.swift
  Togather/Togather/Model/LookUpPostDetailModel.swift
  Togather/Togather/Model/LookUpPostModel.swift
  Togather/Togather/Model/LookUpTagPostModel.swift
  Togather/Togather/Model/LookUpUserProfileModel.swift
  Togather/Togather/Model/SearchPostModel.swift
  Togather/Togather/Model/TokenModel.swift
  Togather/Togather/Model/UploadImageModel.swift
Labels: 기능 추가

#53 🔀 :: (#52) ProfileModel 파일 수정
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Model/LookUpMyProfileModel.swift
Labels: 수정

#54 🔀 :: (#51) ViewModel 추가
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/View/SignInView.swift
  Togather/Togather/View/SignUpView/SignUpView.swift
  Togather/Togather/ViewModels/EmailDuplicateViewModel.swift
  Togather/Togather/ViewModels/LoginViewModel.swift
  Togather/Togather/ViewModels/SignUpViewModel.swift
Labels: 기능 추가

#58 🔀 :: (#57) SigninView에 Navigationlink 추가
  Togather/Togather/View/SignInView.swift
Labels: 기능 추가

#60 🔀 :: (#55) post viewmodel 추가
  Togather/Togather/ViewModels/post/PostViewModel.swift
  Togather/Togather/ViewModels/user/LoginViewModel.swift
  Togather/Togather/ViewModels/user/SignUpViewModel.swift
Labels: 기능 추가

#62 🔀 :: (#61) 메일 중복 확인 VM 파일 추가
  Togather/Togather/ViewModels/user/EmailDuplicateViewModel.swift
Labels: 기능 추가

#64 🔀 :: (#63)FlowLayout Components
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/View/HomeView.swift
  Togather/Togather/View/PostDetail.swift
  Togather/Togather/View/SearchView.swift
  Togather/Togather/View/ViewSupporter/TagsFlowLayout.swift
  Togather/Togather/View/WritingView.swift
  Togather/Togather/View/myview ->/MyPost.swift
Labels: 리팩토링

#66 🔀 :: (#65) Model 파일 수정
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Model/LookUpPostDetailModel.swift
  Togather/Togather/Model/LookUpPostModel.swift
  Togather/Togather/Model/post/LookUpTagPostModel.swift
  Togather/Togather/Model/post/MyPostModel.swift
  Togather/Togather/Model/post/PostDetailModel.swift
  Togather/Togather/Model/post/SearchPostModel.swift
  Togather/Togather/Model/post/TagListModel.swift
  Togather/Togather/Model/post/TagSearchModel.swift
  Togather/Togather/Model/post/TitleSearchModel.swift
  Togather/Togather/Model/post/UserPostModel.swift
  Togather/Togather/Model/user/MyProfileModel.swift
  Togather/Togather/Model/user/TokenModel.swift
  Togather/Togather/Model/user/UserProfileModel.swift
Labels: Document

#72 🔀 :: (#69) 글쓰기 기능 추가
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/View/WritingView.swift
Labels: 기능 추가

#71 🔀 :: (#68) Client 리팩토링
  Togather/Togather/MoyaClient/PostClient.swift
  Togather/Togather/MoyaClient/UserClient.swift
Labels: 리팩토링

#74 🔀 :: (#73) postViewModel Tag/List 받아오기 추가
  Togather/Togather/ViewModels/post/PostViewModel.swift
  Togather/Togather/ViewModels/user/EmailDuplicateViewModel.swift
  Togather/Togather/ViewModels/user/EmailVerifyViewModel.swift
  Togather/Togather/ViewModels/user/LoginViewModel.swift
  Togather/Togather/ViewModels/user/SendEmailViewModel.swift
  Togather/Togather/ViewModels/user/SignUpViewModel.swift
Labels: 기능 추가

#78 🔀 :: (#77) 글쓰기 기능 추가
  Togather/Togather/View/WritingView.swift
  Togather/Togather/ViewModels/post/isSuccess.swift
Labels: 기능 추가

#80 🔀 :: (#79) 게시물 목록 get 버그 수정
  Togather/Togather/MoyaClient/PostClient.swift
  Togather/Togather/View/PostDetail.swift
  Togather/Togather/View/SearchView.swift
  Togather/Togather/View/myview ->/MyPost.swift
Labels: 버그수정

#82 🔀 :: (#81) 게시물 불러오기 기능 구현
  Togather/Togather/View/HomeView.swift
  Togather/Togather/View/ShowView.swift
  Togather/Togather/View/TabBarView.swift
Labels: 기능 추가

#84 🔀 :: (#83) post struct 추가
  Togather/Togather/Model/post/UserPostModel.swift
Labels: Document

#86 🔀 :: (#85) PostDetailViewModel
  Togather/Togather/ViewModels/post/HomeViewModel.swift
  Togather/Togather/ViewModels/post/postDetailViewModel.swift
Labels: 기능 추가

#88 🔀 :: (#87) PostDetailView 기능 구현
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/View/HomeView.swift
  Togather/Togather/View/PostDetail.swift
  Togather/Togather/View/SearchView.swift
  Togather/Togather/View/myview ->/MyPost.swift
Labels: 기능 추가

#90 🔀 :: (#89) Posts_Detail struct 추가
  Togather/Togather/Model/post/PostDetailModel.swift
Labels: 기능 추가

#92 🔀 :: (#91) Kingfisher 라이브러리 추가
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 프로젝트 설정

#94 🔀 :: (#93) model 수정
  Togather/Togather/DrawApp.swift
  Togather/Togather/Model/post/MyPostModel.swift
  Togather/Togather/Model/post/PostDetailModel.swift
  Togather/Togather/Model/post/UserPostModel.swift
Labels: 수정

#98 🔀 :: (#97) edit view
  Togather/Togather/View/HomeView.swift
  Togather/Togather/View/PostDetail.swift
  Togather/Togather/View/SearchView.swift
  Togather/Togather/View/WritingView.swift
  Togather/Togather/View/myview ->/MyPost.swift
Labels: 수정

#103 🔀 :: (#102) swiftui-pull-to-refresh 라이브러리 추가
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 프로젝트 설정

#105 🔀 :: (#104) post 클라이언트 수정
  Togather/Togather/MoyaClient/PostClient.swift
Labels: 수정

#108 🔀 :: (#107) 홈 화면 기능 수정
  Togather/Togather/View/HomeView.swift
  Togather/Togather/ViewModels/post/HomeViewModel.swift
Labels: 수정

#109 🔀 :: (#106) 내 게시물 기능 추가
  Togather/Togather/View/HomeView_List_Content.swift
  Togather/Togather/View/myview ->/MyPost.swift
  Togather/Togather/ViewModels/post/MyViewModel
  Togather/Togather/ViewModels/post/MyViewModel.swift
Labels: 기능 추가

#111 🔀 :: (#110) edit code
  Togather/Togather/Model/post/UserPostModel.swift
  Togather/Togather/View/PostDetail.swift
  Togather/Togather/View/WritingView.swift
Labels: 기능 추가, 수정

#117 🔀 :: (#116) is_mine 기능 추가
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Model/post/PostDetailModel.swift
  Togather/Togather/Model/post/UserPostModel.swift
  Togather/Togather/ViewModels/post/postDetailViewModel.swift
Labels: 기능 추가

#119 🔀 :: (#118) EditPostView 기능 추가
  Togather/Togather/View/EditPostView.swift
  Togather/Togather/ViewModels/post/EditPostViewModel.swift
Labels: 기능 추가

#121 🔀 :: (#120) Navigation 추가
  Togather/Togather/View/PostDetail.swift
Labels: 기능 추가

#126 🔀 :: (#124) Moya 디버깅로그 플러그인 추가
  Togather/Togather/MoyaClient/UserClient.swift
  Togather/Togather/Plugin/MoyaLoggerPlugin.swift
  Togather/Togather/ViewModels/post/HomeViewModel.swift
  Togather/Togather/ViewModels/post/MyViewModel.swift
  Togather/Togather/ViewModels/post/PostViewModel.swift
  Togather/Togather/ViewModels/post/SearchViewModel.swift
  Togather/Togather/ViewModels/post/postDetailViewModel.swift
  Togather/Togather/ViewModels/user/Change/ChangeMyInfoViewModel.swift
  Togather/Togather/ViewModels/user/Change/ChangePasswordViewModel.swift
  Togather/Togather/ViewModels/user/Email/EmailDuplicateViewModel.swift
  Togather/Togather/ViewModels/user/Email/EmailVerifyViewModel.swift
  Togather/Togather/ViewModels/user/Email/SendEmailViewModel.swift
  Togather/Togather/ViewModels/user/FindPasswordEmailViewModel.swift
  Togather/Togather/ViewModels/user/Get/GetMyProfileViewModel.swift
  Togather/Togather/ViewModels/user/Get/GetUserProfileViewModel.swift
  Togather/Togather/ViewModels/user/LogOutViewModel.swift
  Togather/Togather/ViewModels/user/LoginViewModel.swift
  Togather/Togather/ViewModels/user/QuitAccountViewModel.swift
  Togather/Togather/ViewModels/user/SignUp/SignUpViewModel.swift
  Togather/Togather/ViewModels/user/Token/TokenAuthViewModel.swift
Labels: 기능 추가

#136 🔀 :: (#135) 개발자들 뷰 추가
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Model/Github_Profile_Image.swift
  Togather/Togather/View/myview ->/Developers.swift
Labels: 기능 추가

#138 🔀 :: (#137) HomeView 애니메이션 추가
  Togather/Togather/View/HomeView.swift
Labels: 기능 추가

#141 🔀 :: (#128) 비밀번호 변경 추가
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Model/user/MyProfileModel.swift
  Togather/Togather/MoyaClient/UserClient.swift
  Togather/Togather/View/MyView.swift
  Togather/Togather/View/PostDetailVIew.swift
  Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordSuccessView.swift
  Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordVerify.swift
  Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordVerifyView.swift
  Togather/Togather/View/myview ->/PasswordChangeView/EnterNewPasswordView.swift
  Togather/Togather/ViewModels/user/Change/ChangePasswordToEmailViewModel.swift
  Togather/Togather/ViewModels/user/Change/ChangePasswordViewModel.swift
  Togather/Togather/ViewModels/user/Get/GetMyProfileViewModel.swift
  Togather/Togather/ViewModels/user/Get/GetUserProfileViewModel.swift
  Togather/Togather/ViewModels/user/LogOutViewModel.swift
  Togather/Togather/ViewModels/user/LoginViewModel.swift
Labels: 기능 추가

#143 🔀 :: (#142) 에러 로그 리팩토링
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Togather/Togather/ViewModels/user/Get/GetMyProfileViewModel.swift
  Togather/Togather/ViewModels/user/Get/GetUserProfileViewModel.swift
  Togather/Togather/ViewModels/user/LogOutViewModel.swift
  Togather/Togather/ViewModels/user/LoginViewModel.swift
  Togather/Togather/ViewModels/user/Token/TokenAuthViewModel.swift
Labels: 리팩토링

#145 🔀 :: (#144) add plugin
  Togather/Togather/ViewModels/post/DeletePostViewModel.swift
  Togather/Togather/ViewModels/post/EditPostViewModel.swift
  Togather/Togather/ViewModels/post/LikePostViewModel.swift
  Togather/Togather/ViewModels/post/postDetailViewModel.swift
  Togather/Togather/ViewModels/user/Token/TokenAuthViewModel.swift
Labels: 수정

#147 🔀 :: (#146) add textfield methods
  Togather/Togather/View/SearchView.swift
  Togather/Togather/View/SignInView.swift
  Togather/Togather/View/myview ->/EditInfo.swift
Labels: 수정

#150 🔀 :: (#148) edit like func
  Togather/Togather/Model/post/PostDetailModel.swift
  Togather/Togather/MoyaClient/PostClient.swift
  Togather/Togather/View/PostDetailVIew.swift
Labels: 수정

#152 🔀 :: (#130) 내 프로필 보기 추가
  Togather/Togather/View/MyView.swift
  Togather/Togather/View/SignUpView/SignUpView.swift
  Togather/Togather/ViewModels/user/Get/GetMyProfileViewModel.swift
Labels: 기능 추가

#156 🔀 :: (#155) 게시물 순서 바꾸기
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Togather/Togather/MoyaClient/PostClient.swift
  Togather/Togather/View/HomeView.swift
Labels: 수정

#157 🔀 :: (#154) link_keyboard 영어만 달 수 있게할거임
  Togather/Togather/View/WritingView.swift
Labels: 수정

#158 🔀 :: (#155) package
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 수정

#159 🔀 :: (#153) package 재설치
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: 수정, 프로젝트 설정

#162 🔀 :: (#161) 탈퇴 기능 추가
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Togather/Togather/Model/user/UserProfileUDModel.swift
  Togather/Togather/MoyaClient/UserClient.swift
  Togather/Togather/View/MyView.swift
  Togather/Togather/View/PostDetailVIew.swift
  Togather/Togather/View/SignInView.swift
  Togather/Togather/View/myview ->/DeleteAccount.swift
  Togather/Togather/View/myview ->/EditInfo.swift
  Togather/Togather/ViewModels/user/LoginViewModel.swift
  Togather/Togather/ViewModels/user/QuitAccount/QuitAccountViewModel.swift
  Togather/Togather/ViewModels/user/QuitAccountViewModel.swift
  Togather/Togather/ViewModels/user/SignUp/SignUpViewModel.swift
Labels: 기능 추가

#165 🔀 :: (#164) 이미지 추가
  Togather/Togather/Assets.xcassets/GrayHeart.imageset/Contents.json
  Togather/Togather/Assets.xcassets/GrayHeart.imageset/GrayHeart.png
  Togather/Togather/Assets.xcassets/SeperateBar.imageset/Contents.json
  Togather/Togather/Assets.xcassets/SeperateBar.imageset/SeperateBar.png
Labels: 수정

#167 🔀 :: (#166) 게시물 하트 추가
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Togather/Togather/Model/post/UserPostModel.swift
  Togather/Togather/View/HomeView.swift
  Togather/Togather/ViewModels/post/HomeViewModel.swift
  Togather/Togather/ViewModels/post/MyViewModel.swift
  Togather/Togather/ViewModels/post/SearchViewModel.swift
Labels: 기능 추가, 뷰

#168 🔀 :: (#163) 로그아웃 기능 추가
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Togather/Togather/View/HomeView.swift
  Togather/Togather/View/MyView.swift
  Togather/Togather/View/TabBarView.swift
  Togather/Togather/ViewModels/user/LogOutViewModel.swift
Labels: 기능 추가

#170 🔀 :: (#169) 글쓰기 태그 기능 업데이트
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/Assets.xcassets/WhiteCheck.imageset/Contents.json
  Togather/Togather/Assets.xcassets/WhiteCheck.imageset/WhiteCheck.svg
  Togather/Togather/View/HomeView.swift
  Togather/Togather/View/PostDetailVIew.swift
  Togather/Togather/View/SearchView.swift
  Togather/Togather/View/TagListView.swift
  Togather/Togather/View/WritingView.swift
  Togather/Togather/View/myview ->/Developers.swift
  Togather/Togather/ViewModels/post/TagViewModel.swift
  Togather/Togather/ViewModels/user/Login/LoginViewModel.swift
  Togather/Togather/ViewModels/user/Logout/LogoutViewModel.swift
  Togather/Togather/ViewModels/user/Profile/GetMyProfileViewModel.swift
  Togather/Togather/ViewModels/user/Profile/GetUserProfileViewModel.swift
Labels: 기능 추가

#174 🔀 :: (#173) ViewModel 비동기 처리
  Togather/Togather/ViewModels/post/EditPostViewModel.swift
  Togather/Togather/ViewModels/post/HomeViewModel.swift
  Togather/Togather/ViewModels/post/MyViewModel.swift
  Togather/Togather/ViewModels/post/PostViewModel.swift
  Togather/Togather/ViewModels/post/SearchViewModel.swift
  Togather/Togather/ViewModels/post/TagViewModel.swift
  Togather/Togather/ViewModels/post/postDetailViewModel.swift
  Togather/Togather/ViewModels/user/Change/ChangePasswordToEmailViewModel.swift
  Togather/Togather/ViewModels/user/Email/EmailVerifyViewModel.swift
  Togather/Togather/ViewModels/user/Login/LoginViewModel.swift
  Togather/Togather/ViewModels/user/Profile/GetMyProfileViewModel.swift
  Togather/Togather/ViewModels/user/SignUp/SignUpViewModel.swift
  Togather/Togather/ViewModels/user/Token/TokenAuthViewModel.swift
Labels: 리팩토링

#179 🔀 :: (#177) 좋아요 기능 버그 수정
  Togather/Togather/View/C언어 ㅋ.c
  Togather/Togather/View/C언어 ㅋ.h
  Togather/Togather/View/PostDetailVIew.swift
  Togather/Togather/ViewModels/post/postDetailViewModel.swift
Labels: 버그수정, 수정

#180 🔀 :: (#178) 태그 검색 수정
  Togather/Togather.xcodeproj/project.pbxproj
  Togather/Togather/View/C언어 ㅋ.c
  Togather/Togather/View/HomeView.swift
  Togather/Togather/View/SearchTagListView.swift
  Togather/Togather/View/SearchView.swift
Labels: 버그수정, 기능 추가

#182 🔀 :: (#181) @available(iOS 16.0, *) 추가
  Togather/Togather.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Togather/Togather/ContentView.swift
  Togather/Togather/DrawApp.swift
  Togather/Togather/View/MyView.swift
  Togather/Togather/View/ShowView.swift
  Togather/Togather/View/SignInView.swift
  Togather/Togather/View/SignUpView/SignUpEmailVerifyView.swift
  Togather/Togather/View/SignUpView/SignUpView.swift
  Togather/Togather/View/SignUpView/signUpSuccessView.swift
  Togather/Togather/View/TabBarView.swift
  Togather/Togather/View/WritingView.swift
  Togather/Togather/View/myview ->/EditInfo.swift
  Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordSuccessView.swift
  Togather/Togather/View/myview ->/PasswordChangeView/ChangePasswordVerifyView.swift
  Togather/Togather/View/myview ->/PasswordChangeView/EnterNewPasswordView.swift
Labels: 기능 추가, 수정
